In [1]:
x = 3
y = 2
print(x and y)

2


In [2]:
lst = [1,2,3,4]
lst.insert(4,5)
lst.extend([10,9,8])
print(lst)
sum(lst)
lst.pop(3)
print(lst)

[1, 2, 3, 4, 5, 10, 9, 8]
[1, 2, 3, 5, 10, 9, 8]


In [3]:
import numpy as np

In [4]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [5]:
print(type(arr))
print(arr.shape)
print(arr.size)
print(arr.nbytes)

<class 'numpy.ndarray'>
(3, 4)
12
48


In [6]:
print(arr.reshape(2,6)[0,2])

3


In [7]:
lst = np.arange(0,10,3)
print(lst)
lst=arr.copy()
print(arr)

[0 3 6 9]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
a = np.random.rand(3,3)
print(a)

[[0.26821522 0.74082577 0.42067049]
 [0.86963142 0.91277204 0.26997236]
 [0.23612557 0.1534276  0.46869017]]


In [9]:
b = np.linspace(1,10,50)
print(b)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [10]:
np.round?
np.linalg.inv?

In [12]:
a = np.random.randint(1,50,size = (2,1))
b = np.random.randint(51,100,size = (2,1))
hstk = np.hstack((a,b))
vstk = np.vstack((a,b))
print("a = ",a,"\nb = ",b)
print("hstack = ",hstk,"\nvstack = ",vstk)
# we can use np.concat(axis = 1 or 0) to replace hstack and vstack
rez1 = np.concatenate((a,b),axis = 0)
rez2 = np.concatenate((a,b),axis = 1)#vertical concat
print("rez1 = ",rez1,"\nrez2 = ",rez2)#horizontal concat

a =  [[ 8]
 [27]] 
b =  [[85]
 [71]]
hstack =  [[ 8 85]
 [27 71]] 
vstack =  [[ 8]
 [27]
 [85]
 [71]]
rez1 =  [[ 8]
 [27]
 [85]
 [71]] 
rez2 =  [[ 8 85]
 [27 71]]


In [17]:
b = np.random.rand(10000000)
%timeit sum(b)
%timeit np.sum(b)

676 ms ± 50.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
11.3 ms ± 252 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
