In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression as lr
sns.set()

In [2]:
data = pd.read_csv('Multiple_linear_regression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [3]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

In [4]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [5]:
reg = lr()
reg.fit(x,y)

LinearRegression()

In [6]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [7]:
reg.intercept_

0.29603261264909353

In [8]:
reg.score(x,y)

0.4066811952814282

In [9]:
def adj_r2(x,y):
    return 1 - ((1-reg.score(x,y))*(x.shape[0]-1)/(x.shape[0] - 1 - x.shape[1]))
print(adj_r2(x,y))

0.39203134825134


In [10]:
from sklearn.feature_selection import f_regression as fr

In [11]:
fr(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [12]:
p_vals = fr(x,y)[1]

In [13]:
p_vals.round(3)

array([0.   , 0.676])